core/urls.py
from doctest import debug
from typing import Any, List
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

admin.site.site_title = "Admin SafeCare"
admin.site.site_header = "Administração do SafeCare"
admin.site.index_title = "Bem-vindo a Administração SafeCare"

urlpatterns: List[Any] = [
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include("events.urls")),
    path("", include("responses.urls")),
    path("", include("investigations.urls")),
    path("", include("manager_responses.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

investigations/urls.py
from django.urls import path
from .views import xpto
urlpatterns = [
    path('xpto/', view=xpto.as_view(), name="xpto")
]

responses/urls.py
from django.urls import path

from responses.views import (
    EventResponseOcurrenceCreateView,
    EventResponseSucessTemplateView,
)

app_name = "responses"

urlpatterns = [
    path(
        "response/<int:pk>/",
        EventResponseOcurrenceCreateView.as_view(),
        name="responseocurrence_create",
    ),
    path(
        "response/<int:pk>/sucess/",
        EventResponseSucessTemplateView.as_view(),
        name="responseocurrence_success",
    ),
]

investigations/models.py
from django.db import models

# Create your models here.

investigations/views.py
from django.shortcuts import render
from django.views import View


# Create your views here.
class xpto(View):
    def get(self, request):
        return render(request, template_name='xpto.html')

investigations/templates/xpto.html
{% extends 'components/_tables.html' %}
{% load static %}

{% block subtitle %} Lista de Investigações para Tratar {% endblock subtitle %}
{% comment %} {% block link %} {% url 'events:eventocurrence_create' %} {% endblock link %} {% endcomment %}
{% block columns %}
    <th>ID</th>
    <th>Setor Notificante</th>
    <th>Setor Notificado</th>
    <th>Data da Ocorrência</th>
    <th>Paciente/Ocorrência</th>
    <th>Ações</th>
{% endblock columns %}

{% block lines %}
    {% for event in events %}
        <tr>
            <td>
                <div class="d-flex gap-2 justify-content-center" >
                    <a href="{% url 'responses:responseocurrence_create' event.id %}" class="text-primary fw-bold">
                        {{ event.id }}
                    </a>
                </div>
            </td>
            <td><div class="d-flex gap-2 justify-content-left" >{{ event.reporting_department }} </div></td>
            <td><div class="d-flex gap-2 justify-content-left" >{{ event.notified_department }} </div></td>
            <td>{{ event.ocurrence_date|date:"d/m/Y" }}</td>
            <td>
            <div class="d-flex gap-2 justify-content-left" >
                {% if event.patient_involved %}
                    <img src="{% static 'assets/img/patient.png' %}" alt="Involves patient">
                    Envolve paciente
                {% else %}
                    <img src="{% static 'assets/img/ocurrence.png' %}" alt="No patient">
                    Não envolve paciente
                {% endif %}
                </div>
            </td>
            <td>
                <div class="d-flex gap-2 justify-content-center">
                    {% if perms.response.add_responseocurrence %}
                        <a href="{% url 'responses:responseocurrence_create' event.id %}" class="btn btn-success btn-sm" title="Adicionar Tratativa">
                            <i class="bi bi-folder"></i>
                        </a>
                    {% endif %}
                <!--MODAL HERE -->
                 <button type="button" class="btn btn-info btn-sm" title="Visualizar" 
                    data-toggle="tooltip" 
                    data-bs-toggle="modal" 
                    data-bs-target="#viewEventModal" 
                    data-id="{{ event.id }}">
                    <i class="bi bi-eye"></i>S
                </button>
                {% if perms.events.delete_eventocurrence %}
                    <a href="{% url 'events:eventocurrence_delete' event.id %}" class="btn btn-danger btn-sm" title="Excluir">
                        <i class="bi bi-trash"></i>
                    </a>
                {% endif %}
                {% include 'event/partial/_event_modal_detail_view.html' %}
                </div>
            </td>
        </tr>
    {% endfor %}
{% endblock lines %}